### ISSUE TITLE
stuck at: Connecting to Steam network.

### ISSUE THREAD

**Issue by SFx2018** [scholtzm/vapor#10]
Since 2 days my bot stuck at:
"Connecting to Steam network"

what can I do?  :(

**Comment by matthewlilley** [comment]
@SFx2018 I don't believe this project is actively maintained anymore.

**Comment by scholtzm** [comment]
You'll need to provide more info. I'm using this library right now and the bot is connected.

**Comment by SFx2018** [comment]
I'm using this script: https://github.com/luk1337/vapor-report

it worked good, but 3-4 days just stopped working and stuck at connecting

https://i.imgur.com/CvugbC0.png

**Comment by scholtzm** [comment]
The issue is caused by the fact that the bundled server list inside `node-steam` is outdated and it only contains dead IPs. See https://github.com/seishun/node-steam/issues/434.

My bot works because I handle:
- `writeFile` event (which provides me with fresh servers.json) (see docs)
- assign contents of `servers.json` to `botInstance.servers` before calling init

Easiest fix would be to download fresh server list from [this comment](https://github.com/seishun/node-steam/issues/434#issuecomment-404778885), save it to a file and assign to `instance.servers`.

```
const bot = vapor();

try {
  bot.servers = require('<data_folder_created_by_fs_plugin>/servers.json');
} catch(error) {
  // probably missing or unparsable
}

bot.use(vapor.plugins.fs);
```

**Comment by SFx2018** [comment]
it works! thank you!

**Comment by koalayby** [comment]
@scholtzm  i have update the server.js, while the bot still cannot connected SteamGC successfully, I know you are pro for this. Could you help to figure out the problem?  Regards and Thanks!

**Comment by scholtzm** [comment]
You must have done something wrong because the fix does work. `server.js` is probably your file and I don't know the contents of this file.
